services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: communityhub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: s3crect
    ports:
      - "5432:5432"
    volumes:
      - postgres_sql:/var/lib/postgresql/data

  keycloak:
    build:
      context: ./docker/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"

  app:
    build:
      context: .
    depends_on:
      - postgresql
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/communityhub
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: s3crect
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/communityhub
      APP_SECURITY_JWT_AUDIENCE: communityhub-api
    ports:
      - "8080:8080"
volumes:
  postgres_sql:
