services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: communityhub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: s3crect
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
