spring:
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5432/communityhub
    password: s3crect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: 'false'
app:
  jwt:
    secret: change-me-please-change-me-please-change-me
    expiration-seconds: '86400'
