spring:
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: validate
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5432/communityhub
    password: s3crect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: 'false'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/communityhub
app:
  security:
    jwt:
      audience: communityhub-api
