spring:
  profiles:
    active: dev
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: validate
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5432/communityhub
    password: s3crect
app:
  security:
    jwt:
      audience: communityhub-api
